name: Test Final

on:
  push:
    branches: [ test-final ]

jobs:
  test:
    runs-on: self-hosted  # lo más simple posible
    steps:
      - run: echo "¡Funciona!"
      - run: docker --version
      - run: hostname